{{- if and .Values.pyroscopeagent.enabled (not .Values.pyroscopeagent.agent.configMap.create) }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "pyroscope.labels" . | nindent 4 }}
  name: {{ .Values.pyroscopeagent.agent.configMap.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  namespace: {{ .Release.Namespace }}
data:
  config.river: |
    discovery.kubernetes "local_pods" {
        selectors {
        field = "spec.nodeName=" + env("HOSTNAME")
        role = "pod"
        }
        role = "pod"
    }
    pyroscope.ebpf "instance" {
        forward_to = [pyroscope.write.pyroscope_write.receiver]
        targets = discovery.kubernetes.local_pods.targets
    }
    pyroscope.write "pyroscope_write" {
        endpoint {
          {{- if hasKey .Values.pyroscope.pyroscope.components "distributor" }}
          url = "http://{{ include "pyroscope.fullname" . }}-distributor.{{ .Release.Namespace }}.svc.cluster.local.:{{ (.Values.pyroscope.pyroscope.components.distributor.service).port | default .Values.pyroscope.pyroscope.service.port}}"
          {{- else }}
          url = "http://{{ include "pyroscope.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local.:{{ .Values.pyroscope.pyroscope.service.port }}"
          {{- end }}
        }
    }
{{- end }}
