{{- if .Values.psp.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations: 
    "helm.sh/hook": "pre-install,pre-upgrade"
  labels:
    {{- include "pyroscope.labels" . | nindent 4 }}
  name: {{ .Values.psp.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.psp.name }}
subjects:
- kind: ServiceAccount
  name: {{ include "pyroscope.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}