{{- if .Values.pyroscopeagent.enabled }}
{{- if not .Values.pyroscopeagent.agent.configMap.create }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
    "helm.sh/hook": pre-install,pre-upgrade
  labels:
    {{- include "pyroscope.labels" . | nindent 4 }}
  name: pyroscope-agent
spec:
  fsGroup:
    rule: RunAsAny
  privileged: true
  readOnlyRootFilesystem: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - hostPath
  - secret
  - emptyDir
  - projected
  - configMap
{{- end }}
{{- end }}
