{{- if .Values.psp.enabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations: 
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
    "helm.sh/hook": "pre-install,pre-upgrade"
  labels:
    {{- include "pyroscope.labels" . | nindent 4 }}
  name: {{ .Values.psp.name }}
spec:
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  volumes:
  - hostPath
  - secret
  - emptyDir
  - projected
  - configMap
  - persistentVolumeClaim
{{- end }}
