version: 2.1
orbs:
  architect: giantswarm/architect@5.11.6

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: architect
          executor: app-build-suite
          name: package-and-push-chart
          app_catalog: giantswarm-playground-catalog
          app_catalog_test: giantswarm-playground-test-catalog
          ct_config: ".circleci/ct-config.yaml"
          chart: "pyroscope"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
